I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 42, in script
    image chap1_movie = Movie(size=(1920, 1080), channel='movie', play="images/chap1.webm")
  File "game/script.rpy", line 42, in <module>
    image chap1_movie = Movie(size=(1920, 1080), channel='movie', play="images/chap1.webm")
TypeError: __init__() got an unexpected keyword argument 'size'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 42, in script
    image chap1_movie = Movie(size=(1920, 1080), channel='movie', play="images/chap1.webm")
  File "/Applications/renpy-8.3.2-sdk/renpy/ast.py", line 920, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Applications/renpy-8.3.2-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 42, in <module>
    image chap1_movie = Movie(size=(1920, 1080), channel='movie', play="images/chap1.webm")
TypeError: __init__() got an unexpected keyword argument 'size'

macOS-14.0-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
star team 1.0
Thu Oct 24 13:39:43 2024
