I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1673, in script
    if chosen_movie == "movie1":
  File "game/script.rpy", line 1673, in <module>
    if chosen_movie == "movie1":
NameError: name 'chosen_movie' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1673, in script
    if chosen_movie == "movie1":
  File "/Applications/renpy-8.3.2-sdk/renpy/ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "/Applications/renpy-8.3.2-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-8.3.2-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1673, in <module>
    if chosen_movie == "movie1":
NameError: name 'chosen_movie' is not defined

macOS-14.0-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
star team 1.0
Thu Feb 27 16:02:54 2025
