I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 783, in script
    python:
  File "game/script.rpy", line 784, in <module>
    movie_choices = get_two_movies_of_type("trendiness")
  File "game/script.rpy", line 37, in get_two_movies_of_type
    with open(movie_data_fp, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/siddharthiyer/Documents/GitHub/star-team-japanlab/star team/game/csv files/Movie DB - prewar movies.csv'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 783, in script
    python:
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 784, in <module>
    movie_choices = get_two_movies_of_type("trendiness")
  File "game/script.rpy", line 37, in get_two_movies_of_type
    with open(movie_data_fp, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/siddharthiyer/Documents/GitHub/star-team-japanlab/star team/game/csv files/Movie DB - prewar movies.csv'

macOS-14.1-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
star team 1.0
Mon Nov 18 13:14:03 2024
