I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 791, in script
    python:
  File "game/script.rpy", line 792, in <module>
    movie_choices = get_two_movies_of_type("trendiness")
  File "game/script.rpy", line 70, in get_two_movies_of_type
    with open(movie_data_fp, 'r') as file:
TypeError: expected str, bytes or os.PathLike object, not StringIO

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 791, in script
    python:
  File "/Applications/renpy-8.3.2-sdk/renpy/ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-8.3.2-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 792, in <module>
    movie_choices = get_two_movies_of_type("trendiness")
  File "game/script.rpy", line 70, in get_two_movies_of_type
    with open(movie_data_fp, 'r') as file:
TypeError: expected str, bytes or os.PathLike object, not StringIO

macOS-14.1-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
star team 1.0
Sat Mar  1 22:06:42 2025
